### PR TITLE
added discount_amount_cart field

### PR DESCRIPTION
**Pull request by claretcrab**

### CODE REVIEW

**Comment by claretcrab** [comment]
Added discount_amount_cart as a hidden field

**Comment by alch** [comment]
This adds a discount line in the paypal confirmation form. 

See [here](https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/Appx_websitestandard_htmlvariables/#id08A6HH0D0TA)

**Comment by alch** [comment]
Merging and tagging

**Comment by mickaelandrieu** [comment]
:+1:  sorry I'm so busy, it's all on you @alch !

**Comment by alch** [comment]
@mickaelandrieu thanks :+1:

**Pull request merged**
